# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d8387ad9c1e1b1c378147ecd9e4f18010609a1dfa25573e485499e60cb517f95e27b573169631203f6481579171b2560723b2010f60fdbc22d843f069a390b

test:
  secret_key_base: 0f5d8319099d5c9bdba17100625d0b0cbbe2fe96a1c3680efad4f4d25c707ed7c39a12df3a5449e3544d3f65571f2019fcba9a7f3b80361b271f847285292002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
