# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f0d3660a1c195538f4ebfcc356b39fea7457ea6181c611e6c0b27e6a8539edd25dc7e5ca004b72f63a66f7233b9e30c0711525e10dc3b08fd20bbb9a4ab7ae

test:
  secret_key_base: e515e8e42d25127081ef8fbbb2a40d8aed44e675939d9253e7c58ad3798911059d75d899ae3d904a524e550a9edb79b241083e350db5574cde129f73e6abaaf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
